-- 1. CREATE TABLE WITH ALL CUSTOMER_IDS
DROP TABLE IF EXISTS dws.arketip;

CREATE TABLE dws.arketip AS
SELECT customer_id
FROM (
    SELECT DISTINCT customer_id::text AS customer_id FROM dws.digital_actions
    UNION
    SELECT DISTINCT customer_id::text AS customer_id FROM dws.actions
    UNION
    SELECT DISTINCT customer_id::text AS customer_id FROM dws.member_details
) u;


-- 2. ADD METRIC COLUMNS
ALTER TABLE dws.arketip
ADD COLUMN katilim_yatirim INTEGER DEFAULT 0,
ADD COLUMN addBankAccount INTEGER DEFAULT 0,
ADD COLUMN settings INTEGER DEFAULT 0,
ADD COLUMN bes INTEGER DEFAULT 0,
ADD COLUMN otonom INTEGER DEFAULT 0,
ADD COLUMN pushNotification INTEGER DEFAULT 0,
ADD COLUMN compare INTEGER DEFAULT 0,
ADD COLUMN filterselection INTEGER DEFAULT 0,
ADD COLUMN sorting INTEGER DEFAULT 0,
ADD COLUMN otonombuy INTEGER DEFAULT 0,
ADD COLUMN transactionsHistory INTEGER DEFAULT 0,
ADD COLUMN generalsummary INTEGER DEFAULT 0,
ADD COLUMN background INTEGER DEFAULT 0,
ADD COLUMN foreground INTEGER DEFAULT 0,
ADD COLUMN canceltransaction INTEGER DEFAULT 0,
ADD COLUMN grihelpcenter INTEGER DEFAULT 0,
ADD COLUMN signup_night INTEGER DEFAULT 0,
ADD COLUMN signin_night INTEGER DEFAULT 0,
ADD COLUMN order_night INTEGER DEFAULT 0,
ADD COLUMN addfavourite INTEGER DEFAULT 0,
ADD COLUMN age_28_48 INTEGER DEFAULT 0,
ADD COLUMN has_account_ready INTEGER DEFAULT 0,
ADD COLUMN faiz_okey INTEGER DEFAULT 0,
ADD COLUMN video_izleyen INTEGER DEFAULT 0,
ADD COLUMN dya_gece INTEGER DEFAULT 0,
ADD COLUMN katilim_ilgi INTEGER DEFAULT 0,
ADD COLUMN dya_score INTEGER DEFAULT 0;
ADD COLUMN popular_fund_ratio FLOAT;
ADD COLUMN yeni_portfoy INTEGER;
ADD COLUMN birden_fazla_banka_hesabi INTEGER;
